spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5432/week12_orders
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
#    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql

server:
  servlet:
    context-path: /orders
  port: 9020


#eureka-config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


resilience4j:
  retry:
    configs: #we can use configs to avoid repeating similar across various instances
      default:
        max-attempts: 3
        wait-duration: 100ms
    instances:
      inventoryRetry:
        max-attempts: 3 #number of times it'll try, after that moves to fallbackMethod
        wait-duration: 5s #durating it'll wait before next retry

  ratelimiter:
    instances:
      inventoryRateLimiter:
        limit-for-period: 1 #Max calls allowed per period
        limit-refresh-period: 5s #How often the limit resets
        timeout-duration: 2s #How long a call waits for a permit before throwing an exception

  circuitbreaker:
    instances:
      inventoryCircuitBreaker:
        register-health-indicator: true #expose circuit breaker health via the actuator
        sliding-window-size: 10 #size of sliding window for call recording (How many recent calls to measure)
        sliding-window-type: COUNT_BASED #use count-based sliding window
        minimum-number-of-calls: 10 #min no. of calls before calculating failure rate
        failure-rate-threshold: 50 #if 50% (5/10) calls fail, the circuit goes to open state
        wait-duration-in-open-state: 20s #time the circuit stays open, before moving to HALF_OPEN
        permitted-number-of-calls-in-half-open-state: 3 #number of test calls in half-open state
        event-consumer-buffer-size: 10 #buffer size for event logs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  info:
    java:
      enabled: true


