spring.application.name=inventory-service
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#to connect our local mysql to spring data jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/week12dbp1
spring.datasource.password=root
spring.datasource.username=postgres

#for data.sql to be loaded every time into db, useful in case of ddl-auto=create/create-drop, as every time application restarts, it drops the previous tables
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql


server.port=9010
server.servlet.context-path=/api/v1

#eureka-config
eureka.client.service-url.defaultZone= http://localhost:8761/eureka