apiVersion: v1
kind: Secret
metadata:
  name: my-sercret
type: kubernetes.io/basic-auth
data:
  DB_USER: dXNlcg== # base64 of 'user'
  DB_PASSWORD: cm9vdA== # base64 of 'root'
  INVENTORY_DB_NAME: <BASE64_NAME>
  ORDER_DB_NAME: <BASE64_NAME>